name: covcopcomp_math_fact
description: A new Flutter project.

# The following line prevents the package from being accidentally published to
# pub.dev using `flutter pub publish`. This is preferred for private packages.
publish_to: 'none' # Remove this line if you wish to publish to pub.dev

version: 1.0.0+1

environment:
  sdk: ">=2.10.0 <3.0.0"

dependencies:
  flutter:
    sdk: flutter
  cupertino_icons: ^1.0.2
  firebase_auth: ^3.3.7
  cloud_firestore: ^3.1.8
  firebase_core: ^1.12.0
  provider: ^6.0.2
  flutter_spinkit: ^5.1.0
  flutter_svg: ^1.0.3

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^1.0.0

flutter:
  uses-material-design: true
  assets:
  - assets/images/add.svg
  - assets/images/divide.svg
  - assets/images/subtract.svg
  - assets/images/multiply.svg
  - assets/images/equals.svg
  - assets/images/one.svg
  - assets/images/two.svg
  - assets/images/three.svg
  - assets/images/four.svg
  - assets/images/five.svg
  - assets/images/six.svg
  - assets/images/seven.svg
  - assets/images/eight.svg
  - assets/images/nine.svg
  - assets/images/zero.svg

